### PR TITLE
feat: instrument with IBM Telemetry

### PR DESCRIPTION
**Pull request by francinelucca**
### Description

Adds config file and dependency necessary to start tracking telemetry data via [IBM Telemetry](https://github.com/ibm-telemetry/telemetry-js)

### Changelog

**New**

- Adds @ibm/telemetry-js dependency
- Adds [telemetry.yml](telemetry.yml) config file
- Adds readme telemetry disclosure
- Include `telemetry.yml` in package.json files config 
- Adds postinstall script to enable telemetry run

### Review
Please look through package.json config file and ensure all necessary modifications have been made so that the "telemetry.yml" config file is included in the release version of this package.

**PLEASE NOTE:** In order for IBM Telemetry to start collecting data for this project, a new build must be published including these changes.

### CODE REVIEW

**Comment by lee-chase** [comment]
Hi @francinelucca I split in two last week, probably around the same time you added this PR.

So `main-v2` is the current version running on an old version of stylelint. 

`main` is stylelint 16 which is largely the same code with ESM modules only.

Should this change be targetting `main-v2`? 

I can create a second PR for v3 if needed.  

Plus you removed a dependency `"@carbon/themes-10": "npm:@carbon/themes@^10.54.0",` was that deliberate?

**Comment by francinelucca** [comment]
> So main-v2 is the current version running on an old version of stylelint.

> main is stylelint 16 which is largely the same code with ESM modules only.

Are both of these versions being deployed? If so we want both 

> Plus you removed a dependency "@carbon/themes-10": "npm:@carbon/themes@^10.54.0", was that deliberate?

That was an oversight, I'll fix!

@lee-chase

**Comment by francinelucca** [comment]
@lee-chase fixed up the conflicts here and readded `@carbon/themes-10`. When I `yarn` installed, a couple of offline-yarn mirrors changed, not sure what that's about...

Let me know if `main-v2` needs to be instrumented as well and I can open a PR for that too!

**Comment by lee-chase** [comment]
Both main and main_v2 will be deployed for now. V3 `main` is ESM only to support `stylelint 16` it may be some time before teams move only the latest stylelint.

**Pull request merged**
